/**
 * Standarisasi Kode Error Sistem Bot Denia
 */
export const ErrorCode = {
  // Autentikasi & Otorisasi
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_NOT_REGISTERED: 'USER_NOT_REGISTERED',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',

  // Validasi Slot & Waktu
  INVALID_SLOT_FORMAT: 'INVALID_SLOT_FORMAT',
  INVALID_SLOT_SEQUENCE: 'INVALID_SLOT_SEQUENCE',
  SLOT_LIMIT_EXCEEDED: 'SLOT_LIMIT_EXCEEDED',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  PAST_DATE_NOT_ALLOWED: 'PAST_DATE_NOT_ALLOWED',
  INVALID_BOOKING_LEAD_TIME: 'INVALID_BOOKING_LEAD_TIME',

  // Ruangan & Ketersediaan
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  SLOT_CONFLICT: 'SLOT_CONFLICT',
  FORCE_BLOCKED: 'FORCE_BLOCKED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  NOT_BOOKING_OWNER: 'NOT_BOOKING_OWNER',

  // Sintaks Perintah
  INVALID_COMMAND_SYNTAX: 'INVALID_COMMAND_SYNTAX',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',

  // Sistem & Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
